#!/bin/sh

mkdir "./data/"
# mkdir "./data/AMAZON FASHION"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/AMAZON_FASHION.json.gz" -O "./data/AMAZON FASHION/reviews.json.gz"
# gzip -d "./data/AMAZON FASHION/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_AMAZON_FASHION.json.gz" -O "./data/AMAZON FASHION/metadata.json.gz"
# gzip -d "./data/AMAZON FASHION/metadata.json.gz"
# mkdir "./data/All Beauty"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/All_Beauty.json.gz" -O "./data/All Beauty/reviews.json.gz"
# gzip -d "./data/All Beauty/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_All_Beauty.json.gz" -O "./data/All Beauty/metadata.json.gz"
# gzip -d "./data/All Beauty/metadata.json.gz"
# mkdir "./data/Appliances"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Appliances.json.gz" -O "./data/Appliances/reviews.json.gz"
# gzip -d "./data/Appliances/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Appliances.json.gz" -O "./data/Appliances/metadata.json.gz"
# gzip -d "./data/Appliances/metadata.json.gz"
# mkdir "./data/Arts Crafts and Sewing"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Arts_Crafts_and_Sewing.json.gz" -O "./data/Arts Crafts and Sewing/reviews.json.gz"
# gzip -d "./data/Arts Crafts and Sewing/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Arts_Crafts_and_Sewing.json.gz" -O "./data/Arts Crafts and Sewing/metadata.json.gz"
# gzip -d "./data/Arts Crafts and Sewing/metadata.json.gz"
# mkdir "./data/Automotive"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Automotive.json.gz" -O "./data/Automotive/reviews.json.gz"
# gzip -d "./data/Automotive/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Automotive.json.gz" -O "./data/Automotive/metadata.json.gz"
# gzip -d "./data/Automotive/metadata.json.gz"
mkdir "./data/Books"
wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Books.json.gz" -O "./data/Books/reviews.json.gz"
gzip -d "./data/Books/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Books.json.gz" -O "./data/Books/metadata.json.gz"
# gzip -d "./data/Books/metadata.json.gz"
# mkdir "./data/CDs and Vinyl"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/CDs_and_Vinyl.json.gz" -O "./data/CDs and Vinyl/reviews.json.gz"
# gzip -d "./data/CDs and Vinyl/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_CDs_and_Vinyl.json.gz" -O "./data/CDs and Vinyl/metadata.json.gz"
# gzip -d "./data/CDs and Vinyl/metadata.json.gz"
# mkdir "./data/Cell Phones and Accessories"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Cell_Phones_and_Accessories.json.gz" -O "./data/Cell Phones and Accessories/reviews.json.gz"
# gzip -d "./data/Cell Phones and Accessories/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Cell_Phones_and_Accessories.json.gz" -O "./data/Cell Phones and Accessories/metadata.json.gz"
# gzip -d "./data/Cell Phones and Accessories/metadata.json.gz"
# mkdir "./data/Clothing Shoes and Jewelry"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Clothing_Shoes_and_Jewelry.json.gz" -O "./data/Clothing Shoes and Jewelry/reviews.json.gz"
# gzip -d "./data/Clothing Shoes and Jewelry/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Clothing_Shoes_and_Jewelry.json.gz" -O "./data/Clothing Shoes and Jewelry/metadata.json.gz"
# gzip -d "./data/Clothing Shoes and Jewelry/metadata.json.gz"
# mkdir "./data/Digital Music"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Digital_Music.json.gz" -O "./data/Digital Music/reviews.json.gz"
# gzip -d "./data/Digital Music/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Digital_Music.json.gz" -O "./data/Digital Music/metadata.json.gz"
# gzip -d "./data/Digital Music/metadata.json.gz"
# mkdir "./data/Electronics"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Electronics.json.gz" -O "./data/Electronics/reviews.json.gz"
# gzip -d "./data/Electronics/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Electronics.json.gz" -O "./data/Electronics/metadata.json.gz"
# gzip -d "./data/Electronics/metadata.json.gz"
# mkdir "./data/Gift Cards"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Gift_Cards.json.gz" -O "./data/Gift Cards/reviews.json.gz"
# gzip -d "./data/Gift Cards/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Gift_Cards.json.gz" -O "./data/Gift Cards/metadata.json.gz"
# gzip -d "./data/Gift Cards/metadata.json.gz"
# mkdir "./data/Grocery and Gourmet Food"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Grocery_and_Gourmet_Food.json.gz" -O "./data/Grocery and Gourmet Food/reviews.json.gz"
# gzip -d "./data/Grocery and Gourmet Food/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Grocery_and_Gourmet_Food.json.gz" -O "./data/Grocery and Gourmet Food/metadata.json.gz"
# gzip -d "./data/Grocery and Gourmet Food/metadata.json.gz"
# mkdir "./data/Home and Kitchen"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Home_and_Kitchen.json.gz" -O "./data/Home and Kitchen/reviews.json.gz"
# gzip -d "./data/Home and Kitchen/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Home_and_Kitchen.json.gz" -O "./data/Home and Kitchen/metadata.json.gz"
# gzip -d "./data/Home and Kitchen/metadata.json.gz"
# mkdir "./data/Industrial and Scientific"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Industrial_and_Scientific.json.gz" -O "./data/Industrial and Scientific/reviews.json.gz"
# gzip -d "./data/Industrial and Scientific/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Industrial_and_Scientific.json.gz" -O "./data/Industrial and Scientific/metadata.json.gz"
# gzip -d "./data/Industrial and Scientific/metadata.json.gz"
mkdir "./data/Kindle Store"
wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Kindle_Store.json.gz" -O "./data/Kindle Store/reviews.json.gz"
gzip -d "./data/Kindle Store/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Kindle_Store.json.gz" -O "./data/Kindle Store/metadata.json.gz"
# gzip -d "./data/Kindle Store/metadata.json.gz"
# mkdir "./data/Luxury Beauty"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Luxury_Beauty.json.gz" -O "./data/Luxury Beauty/reviews.json.gz"
# gzip -d "./data/Luxury Beauty/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Luxury_Beauty.json.gz" -O "./data/Luxury Beauty/metadata.json.gz"
# gzip -d "./data/Luxury Beauty/metadata.json.gz"
# mkdir "./data/Magazine Subscriptions"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Magazine_Subscriptions.json.gz" -O "./data/Magazine Subscriptions/reviews.json.gz"
# gzip -d "./data/Magazine Subscriptions/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Magazine_Subscriptions.json.gz" -O "./data/Magazine Subscriptions/metadata.json.gz"
# gzip -d "./data/Magazine Subscriptions/metadata.json.gz"
# mkdir "./data/Movies and TV"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Movies_and_TV.json.gz" -O "./data/Movies and TV/reviews.json.gz"
# gzip -d "./data/Movies and TV/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Movies_and_TV.json.gz" -O "./data/Movies and TV/metadata.json.gz"
# gzip -d "./data/Movies and TV/metadata.json.gz"
# mkdir "./data/Musical Instruments"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Musical_Instruments.json.gz" -O "./data/Musical Instruments/reviews.json.gz"
# gzip -d "./data/Musical Instruments/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Musical_Instruments.json.gz" -O "./data/Musical Instruments/metadata.json.gz"
# gzip -d "./data/Musical Instruments/metadata.json.gz"
# mkdir "./data/Office Products"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Office_Products.json.gz" -O "./data/Office Products/reviews.json.gz"
# gzip -d "./data/Office Products/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Office_Products.json.gz" -O "./data/Office Products/metadata.json.gz"
# gzip -d "./data/Office Products/metadata.json.gz"
# mkdir "./data/Patio Lawn and Garden"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Patio_Lawn_and_Garden.json.gz" -O "./data/Patio Lawn and Garden/reviews.json.gz"
# gzip -d "./data/Patio Lawn and Garden/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Patio_Lawn_and_Garden.json.gz" -O "./data/Patio Lawn and Garden/metadata.json.gz"
# gzip -d "./data/Patio Lawn and Garden/metadata.json.gz"
# mkdir "./data/Pet Supplies"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Pet_Supplies.json.gz" -O "./data/Pet Supplies/reviews.json.gz"
# gzip -d "./data/Pet Supplies/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Pet_Supplies.json.gz" -O "./data/Pet Supplies/metadata.json.gz"
# gzip -d "./data/Pet Supplies/metadata.json.gz"
# mkdir "./data/Prime Pantry"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Prime_Pantry.json.gz" -O "./data/Prime Pantry/reviews.json.gz"
# gzip -d "./data/Prime Pantry/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Prime_Pantry.json.gz" -O "./data/Prime Pantry/metadata.json.gz"
# gzip -d "./data/Prime Pantry/metadata.json.gz"
# mkdir "./data/Software"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Software.json.gz" -O "./data/Software/reviews.json.gz"
# gzip -d "./data/Software/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Software.json.gz" -O "./data/Software/metadata.json.gz"
# gzip -d "./data/Software/metadata.json.gz"
# mkdir "./data/Sports and Outdoors"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Sports_and_Outdoors.json.gz" -O "./data/Sports and Outdoors/reviews.json.gz"
# gzip -d "./data/Sports and Outdoors/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Sports_and_Outdoors.json.gz" -O "./data/Sports and Outdoors/metadata.json.gz"
# gzip -d "./data/Sports and Outdoors/metadata.json.gz"
# mkdir "./data/Tools and Home Improvement"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Tools_and_Home_Improvement.json.gz" -O "./data/Tools and Home Improvement/reviews.json.gz"
# gzip -d "./data/Tools and Home Improvement/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Tools_and_Home_Improvement.json.gz" -O "./data/Tools and Home Improvement/metadata.json.gz"
# gzip -d "./data/Tools and Home Improvement/metadata.json.gz"
# mkdir "./data/Toys and Games"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Toys_and_Games.json.gz" -O "./data/Toys and Games/reviews.json.gz"
# gzip -d "./data/Toys and Games/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Toys_and_Games.json.gz" -O "./data/Toys and Games/metadata.json.gz"
# gzip -d "./data/Toys and Games/metadata.json.gz"
# mkdir "./data/Video Games"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Video_Games.json.gz" -O "./data/Video Games/reviews.json.gz"
# gzip -d "./data/Video Games/reviews.json.gz"
# wget -c "http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles/meta_Video_Games.json.gz" -O "./data/Video Games/metadata.json.gz"
# gzip -d "./data/Video Games/metadata.json.gz"

